### ISSUE TITLE
ImportError: cannot import name preload_path

### ISSUE THREAD

**Issue by lsmithso** [chrisjbillington/gil_load#2]
Hi: I'd like to contribute a simple gil_load decorator. I tried
forking master but get the following error:

import gil_load 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gil_load/__init__.py", line 1, in <module>
    from .gil_load import init, test, start, stop, get, preload_path
ImportError: cannot import name preload_path

There are no 'preload_path*' files in the repo.

**Comment by chrisjbillington** [comment]
Ah, sorry, master is not functional at the moment - I'm in the middle of adding functionality so that statistics for how long each individual thread is waiting for the GIL can be collected. This is changing how gil_load works considerably, and necessitating that LD_PRELOAD be set in order to do profiling (hence the error talking about "preload path").

It's almost done. I just pushed the unpushed commits I had so far, but there's a little bit of work to be done still. I'll finish it and probably make the context manager myself I think before releasing as a new version.

**Comment by chrisjbillington** [comment]
I know this is very late, but I have made master functional again and released v0. 4. I'll leave this issue open as a feature request for such a decorator, and will likely implement it soon.
